config/routes.rb
Rails.application.routes.draw do
  resources :users, only: [:create, :new, :show]
  resources :bands do
    resources :albums, only: [:new, :create]
  end
  resources :albums, only: [:edit, :show, :update] do
    resources :tracks, only: [:new, :create]
  end
  resources :tracks, only: [:edit, :show, :update]
  resource :session, only: [:new, :create, :destroy]

  root 'sessions#new'
end

app/models/album.rb
class Album < ActiveRecord::Base
  validates :title, presence: true, uniqueness: { scope: :band_id, message: "Band already has an album with this title" }
  before_save :fix_name

  belongs_to :band

  has_many :tracks,
    dependent: :destroy

  def fix_name
    self.title = self.title.titleize
  end
end

app/models/band.rb
class Band < ActiveRecord::Base
  validates :band_name, presence: true
  before_save :fix_name

  has_many :albums,
    dependent: :destroy

  has_many :tracks,
    through: :albums,
    source: :tracks

  def fix_name
    self.band_name = self.band_name.titleize
  end
end

app/models/track.rb
class Track < ActiveRecord::Base
  validates :title, presence: true, uniqueness: { scope: :album_id, message: "Album already has an album with this title" }
  before_save :fix_name

  belongs_to :album

  def fix_name
    self.title = self.title.titleize
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_reader :password

  validates :session_token, presence: true
  validates :user_name, uniqueness: true
  validates :email, uniqueness: true, presence: true
  validates :password_digest, presence: { message: "Password can't be blank" }
  validates :password, length: { minimum: 6, allow_nil: true }
  after_initialize :ensure_session_token

  def self.find_by_credentials(user_name, password)
    user = User.find_by_user_name(user_name)
    return nil if user.nil?
    user.is_password?(password) ? user : nil
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def is_password?(password)
    BCrypt::Password.new(password_digest).is_password?(password)
  end

  def self.generate_session_token
    SecureRandom.urlsafe_base64(16)
  end

  def reset_session_token!
    self.session_token = self.class.generate_session_token
    self.save!
    self.session_token
  end

  def ensure_session_token
    self.session_token ||= self.class.generate_session_token
  end

end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController

  def new
    @album = Album.new(band_id: params[:band_id].to_i)
    render :new
  end

  def create
    @album = Album.new(album_params)
    if @album.save
      redirect_to album_url(@album)
    else
      flash.now[:errors] = @album.errors.full_messages
      render :new
    end
  end

  def show
    @album = Album.find_by_id(params[:id])
    render :show
  end

  def edit

  end

  def update

  end

  def destroy
    @album = Album.find(params[:id])
    if @album.destroy
      redirect_to albums_url
    else
      redirect_to edit_album_url
    end
  end

  private
  def album_params
    params.require(:album).permit(:title, :band_id, :live)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user

  def log_in_user!(user)
    @current_user = user
    session[:session_token] = user.session_token
  end

  def current_user
    return nil if session[:session_token].nil?
    @current_user ||= User.find_by(session_token: session[:session_token])
  end

  def logged_in?
    return true if current_user
    false
  end
end

app/controllers/bands_controller.rb
class BandsController < ApplicationController

  def new
    @band = Band.new
    render :new
  end

  def create
    @band = Band.new(band_params)
    if @band.save
      redirect_to band_url(@band)
    else
      flash.now[:errors] = @band.errors.full_messages
      render :new
    end
  end

  def show
    @band = Band.find_by_id(params[:id])
    render :show
  end

  def edit
    @band = Band.find_by_id(params[:id])
    render :edit
  end

  def update
    @band = Band.find(params[:id])
    if @band.update_attributes(band_params)
      redirect_to band_url(@band)
    else
      flash.now[:errors] = @band.errors.full_messages
      render :edit
    end
  end

  def destroy
    @band = Band.find(params[:id])
    if @band.destroy
      redirect_to bands_url
    else
      redirect_to edit_band_url
    end
  end

  private
  def band_params
    params.require(:band).permit(:band_name)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    if current_user
      redirect_to bands_url
    else
      @user = User.new
      render :new
    end
  end

  def create
    @user = User.find_by_credentials(params[:user][:user_name], params[:user][:password])
    if @user
      session[:session_token] = @user.reset_session_token!
      redirect_to user_url(@user)
    else
      flash.now[:errors] = ["Invalid Credentials"]
      @user = User.new(user_name: params[:user][:user_name])
      render :new
    end
  end

  def destroy
    if current_user
      current_user.reset_session_token!
      session[:session_token] = nil
    end
    redirect_to new_session_url
  end
end

app/controllers/tracks_controller.rb
class TracksController < ApplicationController

  def new
    @track = Track.new(album_id: params[:album_id].to_i)
    render :new
  end

  def create
    @track = Track.new(track_params)
    if @track.save
      redirect_to track_url(@track)
    else
      flash.now[:errors] = @track.errors.full_messages
      render :new
    end
  end

  def show
    @track = Track.find_by_id(params[:id])
    render :show
  end

  def edit

  end

  def update

  end

  def destroy
    @track = Track.find(params[:id])
    if @track.destroy
      redirect_to tracks_url
    else
      redirect_to edit_track_url
    end
  end

  private
  def track_params
    params.require(:track).permit(:title, :album_id, :bonus)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    if current_user
      redirect_to bands_url
    else
      @user = User.new
      render :new
    end
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in_user!(@user)
      redirect_to user_url(@user)
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end
  end

  private
  def user_params
    params.require(:user).permit(:user_name, :password, :email, :session_token)
  end
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bands_helper.rb
module BandsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tracks_helper.rb
module TracksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/albums/new.html.erb
<h1>New Album</h1>

<%= render "shared/errors" %>

<form class="album" action="<%= band_albums_url %>" method="post">
  <input
     name="authenticity_token"
     type="hidden"
     value="<%= form_authenticity_token %>">

  <select class="band" name="album[band_id]">
    <option></option>
    <% Band.all.each do |band| %>
      <option <%= @album.band_id == band.id ? "selected" : "" %> value=<%= band.id %>><%= band.band_name %></option>
    <% end %>
  </select>

  <input type="text" name="album[title]" value="<%= @album.title %>"></br></br>

  <input type="radio" name="album[live]" value="true">Live</br>
  <input type="radio" name="album[live]" value="false">Studio</br>

  <input type="submit">
</form>

app/views/albums/show.html.erb
<h1><%= @album.title %></h1>
<h2>By <%= link_to @album.band.band_name, band_url(@album.band) %></h2>
<form action="<%= edit_album_url %>" method="get">
  <input type="submit" value="Edit Album">
</form><br/>

<% @album.tracks.each do |track| %>
  <%= link_to track.title, track_url(track) %></br>
<% end %>

</br>
<form action="<%= new_album_track_url(@album) %>" method="get">
  <input type="submit" value="New Track">
</form>

app/views/bands/_form.html.erb
<% action = (band.persisted? ? band_url : bands_url) %>
<% method = (band.persisted? ? :patch : :post) %>

<%= render "shared/errors" %>

<form class="album" action="<%= action %>" method="post">
  <input type="hidden" name="_method" value="<%= method %>">
  <input
     name="authenticity_token"
     type="hidden"
     value="<%= form_authenticity_token %>">

  <input type="text" name="band[band_name]" value="<%= @band.band_name %>"></br></br>
  <input type="submit">
</form>

<% if band.persisted? %>
  <form action="<%= band_url %>" method="post">
    <input type="hidden" name="_method" value="delete">
    <input
       name="authenticity_token"
       type="hidden"
       value="<%= form_authenticity_token %>">
    <input type="submit" value="Delete Band">
  </form>
<% end %>

app/views/bands/edit.html.erb
<h1>Edit Band</h1>

<%= render "form", band: @band %>

app/views/bands/index.html.erb
<h1>Bands</h1>
<br/>
<% Band.all.each do |band|%>
  <%= link_to band.band_name, band_url(band) %><br/>
  <% band.albums.each do |album| %>
    <%= "--" + album.title %><br/>
  <% end %><br/>
<% end %>

</br>
<form action="<%= new_band_url %>" method="get">
  <input type="submit" value="New Band">
</form>

app/views/bands/new.html.erb
<h1>New Band</h1>

<%= render "form", band: @band %>

app/views/bands/show.html.erb
<h1><%= @band.band_name %></h1>
<form action="<%= edit_band_url %>" method="get">
  <input type="submit" value="Edit Band">
</form><br/>

<% @band.albums.each do |album| %>
  <%= link_to album.title, album_url(album) %></br>
<% end %>

</br>
<form action="<%= new_band_album_url(@band) %>" method="get">
  <input type="submit" value="New Album">
</form>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MusicApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<header>
<% if current_user %>
  <%= current_user.user_name %>
  <form class="" action="<%= session_url %>" method="post">
    <input
     name="authenticity_token"
     type="hidden"
     value="<%= form_authenticity_token %>">
    <input type="hidden" name="_method" value="delete">
    <input type="submit" value="Log Out">
  </form>
<% end %>
<% unless bands_url == request.original_url %>
  <div align="center">
    <form class="" action="<%= bands_url %>" method="get">
      <input type="submit" value="Bands List">
    </form>
  </div>
<% end %>
</header>
<body>

<%= yield %>

</body>
</html>

app/views/shared/_errors.html.erb
<% if flash[:errors] %>
  <ul>
  <% flash[:errors].each do |error| %>
    <li><%= error %></li>
  <% end %>
  </ul>
<% end %>

app/views/tracks/new.html.erb
<h1>New Track</h1>

<%= render "shared/errors" %>

<form action="<%= album_tracks_url %>" method="post">
  <input
     name="authenticity_token"
     type="hidden"
     value="<%= form_authenticity_token %>">
  <input type="hidden" name="track[album_id]" value="<%= @track.album_id %>">

  <input type="text" name="track[title]" value="<%= @track.title %>"></br>
  <input type="checkbox" name="track[bonus]" value=true <%= @track.bonus ? "checked" : "" %>>Bonus Track
  </br>
  <input type="submit">
</form>

app/views/tracks/show.html.erb
<h1><%= @track.title %></h1>
<h2>From <%= link_to @track.album.title, album_url(@track.album) %></h2>
<form action="<%= edit_track_url %>" method="get">
  <input type="submit" value="Edit Track">
</form>

app/views/users/_form.html.erb
<form class="user" action="<%= users_url %>" method="post">
  <input
     name="authenticity_token"
     type="hidden"
     value="<%= form_authenticity_token %>">
  <input
     name="_method"
     type="hidden"
     value="post">

  <label for="username">Username:</label><br/>
  <input id="username" type="text" name="user[user_name]" value="<%= @user.user_name %>"><br/>

  <label for="password">Password:</label><br/>
  <input id="password" type="password" name="user[password]" value=""><br/>

  <label for="email">E-Mail:</label><br/>
  <input id="email" type="text" name="user[email]" value="<%= @user.email %>"><br/>

  <input type="submit">
</form>

app/views/users/new.html.erb
<h1>Sign up</h1>

<%= render "shared/errors" %>

<%= render "form" %>

app/views/users/show.html.erb
<h1>Hello, <%= current_user.user_name %>!</h1>

<%= current_user.email %>

<form action="<%= bands_url %>" method="get">
  <input type="submit">
</form>